# Generated by Django 2.2.28 on 2022-11-23 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_num', models.IntegerField(blank=True, help_text='管理番号', null=True)),
                ('name', models.CharField(help_text='名称', max_length=100)),
                ('images', models.ImageField(blank=True, help_text='画像のURLをそのまま貼り付けても可', null=True, upload_to='equipment/')),
                ('alt_image', models.ImageField(default='imgs/no_image_square.jpg', help_text='代替画像', upload_to='imgs/')),
                ('maker', models.CharField(blank=True, default='不明', help_text='メーカー', max_length=100)),
                ('feature', models.CharField(blank=True, help_text='特徴・色など', max_length=100)),
                ('size', models.CharField(blank=True, help_text='サイズなど', max_length=100)),
                ('num', models.PositiveIntegerField(default=1, help_text='個数・本数')),
                ('URL', models.URLField(blank=True, help_text='販売サイトなどのURLがあれば')),
                ('purchase_date', models.CharField(blank=True, default='不明', help_text='購入時期', max_length=100)),
                ('status', models.CharField(choices=[('非常に良い', '非常に良い'), ('良い', '良い'), ('普通', '普通'), ('悪い', '悪い'), ('非常に悪い', '非常に悪い'), ('使用禁止', '使用禁止'), ('不明', '不明')], help_text='ステータス', max_length=10)),
                ('note', models.TextField(blank=True, help_text='メモ')),
                ('created', models.DateTimeField(blank=True, help_text='作成日', null=True)),
                ('modified', models.DateTimeField(blank=True, help_text='更新日', null=True)),
            ],
            options={
                'verbose_name_plural': '装備リスト',
            },
        ),
        migrations.CreateModel(
            name='Equipmentmaincategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(help_text='メインカテゴリ', max_length=100)),
            ],
            options={
                'verbose_name_plural': '装備のメインカテゴリ',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.PositiveIntegerField(default=0, verbose_name='累計利用回数')),
                ('available', models.CharField(choices=[('不可', '不可'), ('可', '可')], default='可', help_text='装備の利用状況', max_length=10)),
                ('history', models.TextField(blank=True, help_text='利用履歴')),
                ('item_name', models.OneToOneField(help_text='装備名', on_delete=django.db.models.deletion.CASCADE, related_name='related_itemname', to='equip_app.Equipment')),
                ('now_user', models.ForeignKey(blank=True, help_text='現在利用者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='now_user', to=settings.AUTH_USER_MODEL)),
                ('previous_user', models.ForeignKey(blank=True, help_text='最終使用者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '(メンテナンス用)利用履歴',
            },
        ),
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend_date', models.DateTimeField(default=django.utils.timezone.now, help_text='利用開始日')),
                ('lend_span', models.PositiveIntegerField(default=14, help_text='貸出期間(日)')),
                ('return_date', models.DateTimeField(help_text='返却予定日')),
                ('note', models.CharField(blank=True, help_text='メモ欄(最大140文字)', max_length=140)),
                ('item_name', models.OneToOneField(help_text='装備名', on_delete=django.db.models.deletion.CASCADE, related_name='borrow_item', to='equip_app.Equipment')),
                ('user', models.ForeignKey(help_text='利用者', on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '(メンテナンス用)利用状況リスト',
            },
        ),
        migrations.CreateModel(
            name='Equipmentcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='カテゴリ', max_length=100)),
                ('main_category', models.ForeignKey(blank=True, help_text='メインカテゴリ名', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equip_app.Equipmentmaincategory')),
            ],
            options={
                'verbose_name_plural': '装備のサブカテゴリ',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(blank=True, help_text='カテゴリ名', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equip_app.Equipmentcategory'),
        ),
    ]
